  name: Create image

  on:
    push:
        branches: [ main ]
  jobs:
    Docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Build Docker image
          run: docker build . --file Dockerfile --tag webpirat/${{ github.event.repository.name }}:latest --tag webpirat/${{ github.event.repository.name }}:0.${{ github.run_number }}

        - name: Push to Docker Hub
          run: docker push webpirat/${{ github.event.repository.name }} --all-tags
